### ISSUE TITLE
[Windows] Fork support

### ISSUE THREAD

**Issue by lars18th** [vakuum/tcptunnel#10]
Hi,

Using the option "--stay-alive" the connection with the server stays connected when the client disconnects from the "tcptunnel". So, in order to kill the connection this parameter can't be used.

However, without it the tunnel disappears when the first client disconnects. So, it's useful to use the parameter "--fork". But this parameter isn't supported in Windows.

Any idea or workaround?
Thank you!

**Comment by vakuum** [comment]
Hello,

You are right: the fork parameter is not supported by the [MinGW32-based version of tcptunnel](https://github.com/vakuum/tcptunnel#for-windows-mingw32).

But the [Cygwin-based version](https://github.com/vakuum/tcptunnel#for-windows-cygwin) does support it: http://www.vakuumverpackt.de/tcptunnel/tcptunnel-0.8.zip

Can you try this version?

**Comment by lars18th** [comment]
> Can you try this version?

Yes, it works! Thank you!
So, I suggest to comment this in the README: "--fork: not supported in MinGW32 version, instead use the Cygwin version". In fact, without the "fork" parameter this tools is useless.

Regards.

**Comment by vakuum** [comment]
:+1:

There is already a note in the README:

> Note: The MinGW32-based version does not support the fork-based concurrent client handling. If you need this feature under Windows, then you should use the Cygwin-based version.
