### ISSUE TITLE
file descriptor leak

### ISSUE THREAD

**Issue by nigelhorne** [vakuum/tcptunnel#5]
After a bit of time with these options

    ./tcptunnel --local-port=2525 --remote-port=25 --remote-host=localhost  --stay-alive --fork

 I get:

    wait_for_clients: accept(): Too many open files

**Comment by vakuum** [comment]
Does this error happen with a lot of concurrent clients?

What does `ulimit` return?

```
$ ulimit -n
1024

$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63336
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 63336
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

$ cat /proc/sys/fs/file-max
805728
```

The following example has 1 tcptunnel process with 40 concurrent client processes.

The main process with PID 21616 has one open socket from type IPv4 ([tcptunnel.c#L216](https://github.com/vakuum/tcptunnel/blob/034593ba7f564c098749b0cd10c2a4a977ad7824/src/tcptunnel.c#L216)) and 3 other open file descriptors.

The child process with PID 21778 has two open sockets from type IPv4 ([tcptunnel.c#L264](https://github.com/vakuum/tcptunnel/blob/034593ba7f564c098749b0cd10c2a4a977ad7824/src/tcptunnel.c#L264), [tcptunnel.c#L329](https://github.com/vakuum/tcptunnel/blob/034593ba7f564c098749b0cd10c2a4a977ad7824/src/tcptunnel.c#L329)) and also 3 other open file descriptors. 

```
$ ps af
...
21616 pts/9    S+     0:00  \_ ./tcptunnel --local-port=1919 --remote-port=19 --remote-host=127.0.0.1 --fork --stay-alive
21620 pts/9    S+     0:00      \_ ./tcptunnel --local-port=1919 --remote-port=19 --remote-host=127.0.0.1 --fork --stay-alive
21624 pts/9    S+     0:00      \_ ./tcptunnel --local-port=1919 --remote-port=19 --remote-host=127.0.0.1 --fork --stay-alive
21628 pts/9    S+     0:00      \_ ./tcptunnel --local-port=1919 --remote-port=19 --remote-host=127.0.0.1 --fork --stay-alive
...
21770 pts/9    S+     0:00      \_ ./tcptunnel --local-port=1919 --remote-port=19 --remote-host=127.0.0.1 --fork --stay-alive
21774 pts/9    S+     0:00      \_ ./tcptunnel --local-port=1919 --remote-port=19 --remote-host=127.0.0.1 --fork --stay-alive
21778 pts/9    S+     0:00      \_ ./tcptunnel --local-port=1919 --remote-port=19 --remote-host=127.0.0.1 --fork --stay-alive
...

$ lsof -p21616
COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
...
tcptunnel 21616 clemens    0u   CHR  136,9      0t0      12 /dev/pts/9
tcptunnel 21616 clemens    1u   CHR  136,9      0t0      12 /dev/pts/9
tcptunnel 21616 clemens    2u   CHR  136,9      0t0      12 /dev/pts/9
tcptunnel 21616 clemens    3u  IPv4 121906      0t0     TCP *:1919 (LISTEN)

$ ls -la /proc/21616/fd
...
lrwx------ 1 clemens clemens 64 Nov  7 23:26 0 -> /dev/pts/9
lrwx------ 1 clemens clemens 64 Nov  7 23:26 1 -> /dev/pts/9
lrwx------ 1 clemens clemens 64 Nov  7 23:25 2 -> /dev/pts/9
lrwx------ 1 clemens clemens 64 Nov  7 23:26 3 -> socket:[121906]

$ lsof -p21778
COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
...
tcptunnel 21778 clemens    0u   CHR  136,9      0t0      12 /dev/pts/9
tcptunnel 21778 clemens    1u   CHR  136,9      0t0      12 /dev/pts/9
tcptunnel 21778 clemens    2u   CHR  136,9      0t0      12 /dev/pts/9
tcptunnel 21778 clemens    3u  IPv4 121952      0t0     TCP localhost:54094->localhost:chargen (ESTABLISHED)
tcptunnel 21778 clemens    4u  IPv4 119065      0t0     TCP localhost:1919->localhost:60050 (ESTABLISHED)

$ ls -la /proc/21778/fd
...
lrwx------ 1 clemens clemens 64 Nov  7 23:27 0 -> /dev/pts/9
lrwx------ 1 clemens clemens 64 Nov  7 23:27 1 -> /dev/pts/9
lrwx------ 1 clemens clemens 64 Nov  7 23:25 2 -> /dev/pts/9
lrwx------ 1 clemens clemens 64 Nov  7 23:27 3 -> socket:[121952]
lrwx------ 1 clemens clemens 64 Nov  7 23:27 4 -> socket:[119065]
```
Can you check if this is similar to your situation?

**Comment by nigelhorne** [comment]
>  Does this error happen with a lot of concurrent clients?

I don't know, but it's doubtful.

[ps395777]$ ulimit -n
1024
[ps395777]$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1031196
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1031196
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

[ps395777]$ cat /proc/sys/fs/file-max
524288

$ ps af
  PID TTY      STAT   TIME COMMAND
31969 pts/161  Ss     0:00 -bash
20695 pts/161  S+     0:00  \_ ./tcptunnel --local-port=2525 --remote-port=25 --
 8700 pts/53   Ss     0:00 -bash
31344 pts/53   R+     0:00  \_ ps af


[ps395777]$ lsof -p20695
COMMAND     PID    USER   FD   TYPE     DEVICE SIZE/OFF        NODE NAME
tcptunnel 20695 hornenj  cwd    DIR       8,17     4096  9151610218 /home/hornenj/bin
tcptunnel 20695 hornenj  rtd    DIR       8,17     4096 14502316288 /
tcptunnel 20695 hornenj  txt    REG       8,17    19481  6455431371 /home/hornenj/bin/tcptunnel
tcptunnel 20695 hornenj  mem    REG       8,17   149280  1617803327 /lib/x86_64-linux-gnu/ld-2.15.so
tcptunnel 20695 hornenj  mem    REG       8,17  1807032  1617376039 /lib/x86_64-linux-gnu/libc-2.15.so
tcptunnel 20695 hornenj    0u   CHR    136,161      0t0         164 /dev/pts/161
tcptunnel 20695 hornenj    1u   CHR    136,161      0t0         164 /dev/pts/161
tcptunnel 20695 hornenj    2u   CHR    136,161      0t0         164 /dev/pts/161
tcptunnel 20695 hornenj    3u  IPv4 2858883963      0t0         TCP *:2525 (LISTEN)

$ ls -la /proc/20695/fd
total 0
dr-x------ 2 hornenj pg4289228  0 Nov  7 12:30 .
dr-xr-xr-x 7 hornenj pg4289228  0 Nov  7 12:30 ..
lrwx------ 1 hornenj pg4289228 64 Nov  8 06:04 0 -> /dev/pts/161
lrwx------ 1 hornenj pg4289228 64 Nov  8 06:04 1 -> /dev/pts/161
lrwx------ 1 hornenj pg4289228 64 Nov  7 12:30 2 -> /dev/pts/161
lrwx------ 1 hornenj pg4289228 64 Nov  8 06:04 3 -> socket:[2858883963]

**Comment by vakuum** [comment]
@nigelhorne: Is the "Too many open files" error still a problem?

If it is, then run the following script as root like this, while tcptunnel is used in the background:

```bash
$ sudo watch -n 1 bash fds.sh
```

fds.sh:

```bash
#!/bin/bash

echo "processes: $(command ls -1d /proc/[0-9]* | wc -l)"
echo "fds: $(command ls -1 /proc/[0-9]*/fd 2> /dev/null | wc -l)"
echo

for dir in /proc/[0-9]*
do
	if [ ! -d "$dir" ]
	then
		continue
	fi

	name=$(cat "${dir}/comm")
	count=$(command ls -1 "${dir}/fd" | wc -l)

	if ((count < 11))
	then
		continue
	fi

	echo "${count} ${name} ${dir}"
done | sort -n -r
```

The script is executed once a second by `watch` and prints the number of processes, the number of open file descriptors and a list of processes that have more than ten open file descriptors.

Normally, tcptunnel should not show up in this list.

**Comment by nigelhorne** [comment]
I think all is currently well. I've not seen the problem again for some time.

**Comment by vakuum** [comment]
Thank you for your feedback! :+1:
