### ISSUE TITLE
SQL Connection issue

### ISSUE THREAD

**Issue by blackchineykh** [vakuum/tcptunnel#7]
I am trying to use this for sql connection tunneling. Is this supported for sql  server port 1433

**Comment by vakuum** [comment]
You are using MSSQL?

It should work for the scenarios "SQL Server default instance running over TCP" and "SQL Server named instances when they are configured to use a fixed port" described in [Ports Used By the Database Engine](https://msdn.microsoft.com/en-us/library/cc646023.aspx#BKMK_ssde).

You should also use the `--fork` and `--stay-alive` options to handle concurrent database connections.

**Comment by blackchineykh** [comment]
Yes it is MSSQL. Its running over TCP using a fixed port, I did not use the --fork option but --stay-alive was used. I got an error while attempting to login. I will try with the fork option and provide feedback

**Comment by blackchineykh** [comment]
It works!! Thanks man. Only needed to add the fork option.
