### ISSUE TITLE
build_server: bind(): Address already in use

### ISSUE THREAD

**Issue by thefantas** [vakuum/tcptunnel#9]
Hi, i haved this error "build_server: bind(): Address already in use", 
tcptunnel.exe --local-port=3389 --remote-port=61500 --remote-host=xxxxxx.xx

I want to redirect my 3389 traffic to an external server but it tells me that post 3389 and is already in use (RDP), it seems to me that this program what it does is open a port ... what I need is to listen to that port and compose it. regards

**Comment by thefantas** [comment]
Can be with netcat?

**Comment by thefantas** [comment]
ngrok is the solution.

**Comment by vakuum** [comment]
The error "Address already in use" means that another process is already bound to the same port.

Under Windows you can use [TCPView](https://technet.microsoft.com/en-us/sysinternals/tcpview.aspx) to find out which process it is.
